apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: starlight-subtle-top-level-items
  namespace: starlight-subtle-top-level-items
spec:
  secretName: starlight-subtle-top-level-items
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "starlight-subtle-top-level-items.trueberryless.org"
